# Generated by Django 5.0.6 on 2024-06-29 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obraarte',
            options={'permissions': [('can_edit_all_obras', 'Can edit all obras'), ('can_delete_all_obras', 'Can delete all obras')]},
        ),
        migrations.AddField(
            model_name='obraarte',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_creador_api', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obraarte',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_como_artista_api', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obraarte',
            name='estilo',
            field=models.CharField(max_length=50),
        ),
    ]
