# Generated by Django 5.0.6 on 2024-06-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_obraarte_options_obraarte_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obraarte',
            name='estilo',
            field=models.CharField(choices=[('impresionismo', 'Impresionismo'), ('romanticismo', 'Romanticismo'), ('surrealismo', 'Surrealismo')], max_length=50),
        ),
    ]
